### PR TITLE
Adjust timeout waiting for database to 120 seconds

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #27

### CODE REVIEW

**Comment by phil-davis** [comment]
@DeepDiver1975 @PVince81 maybe you guys manage this?
I do not have access to add labels and reviewers.

**Comment by phil-davis** [comment]
@micbar @DeepDiver1975 @PVince81 or anybody who cares.
I can't put labels, or put this in a project for it to get noticed.

**Comment by micbar** [comment]
LGTM

Oracle DB could take a very long time. I had the experiance locally.

**Comment by phil-davis** [comment]
@micbar @PVince81 @DeepDiver1975 anybody - please merge

**Comment by phil-davis** [comment]
ping again - @micbar @PVince81 @DeepDiver1975 please just press the merge button (5 seconds effort)

**Pull request merged**
