### PR TITLE
added further owncloud versions to test upgrade from

### PR DESCRIPTION
**Pull request by patrickjahns**
## Motivation

We are moving forward with later versions - let's add more reference points to test upgrades from

### CODE REVIEW

**Comment by PVince81** [comment]
run again tomorrow, the fix is on master

**Comment by phil-davis** [comment]
master update-testing is passing now. I restarted the drone build for this PR.
Fails when upgrading from 10.1.0 with sqlite:
https://drone.owncloud.com/owncloud/update-testing/408/326
```
There were 2 failures:

1) Test\Files\Storage\LockingTests::testGetLocks
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
+    0 => OC\Lock\Persistent\Lock Object (...)

/drone/src/owncloud/tests/lib/Files/Storage/LockingTests.php:100

2) Test\Lock\Persistent\LockMapperTest::testInsert
Failed asserting that actual size 1 matches expected size 0.

/drone/src/owncloud/tests/lib/Lock/Persistent/LockMapperTest.php:149
```

https://drone.owncloud.com/owncloud/update-testing/408/353
```
There were 2 failures:

1) Test\Files\Storage\LockingTests::testGetLocks
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
+    0 => OC\Lock\Persistent\Lock Object (...)

/drone/src/owncloud/tests/lib/Files/Storage/LockingTests.php:100

2) Test\Lock\Persistent\LockMapperTest::testInsert
Failed asserting that actual size 1 matches expected size 0.

/drone/src/owncloud/tests/lib/Lock/Persistent/LockMapperTest.php:149
```
Is this locking stuff supposed to work with SQlite?

**Comment by PVince81** [comment]
maybe there are stray locks ?

with SQLite we don't have the foreign key with cascade delete, so even if some files were deleted from file cache, their locks might remain...

**Comment by patrickjahns** [comment]
How to proceed here? exclude sqlite for the time being and open a separate issue to investigate this? 

Really would like to increase the matrix

**Comment by PVince81** [comment]
@patrickjahns let's raise an issue to investigate and exclude sqlite.

have the ticket be p2-high and in 10.2 project, next sprint

cc @micbar

**Comment by PVince81** [comment]
I ran the test alone by adding the test name in drone.yml and the failure also happens:
```
[run-phpunit:L10:1s] 
[run-phpunit:L11:2s] F                                                                   1 / 1 (100%)
[run-phpunit:L12:2s] 
[run-phpunit:L13:2s] Time: 763 ms, Memory: 16.00MB
[run-phpunit:L14:2s] 
[run-phpunit:L15:2s] There was 1 failure:
[run-phpunit:L16:2s] 
[run-phpunit:L17:2s] 1) Test\Files\Storage\LockingTests::testGetLocks
[run-phpunit:L18:2s] Failed asserting that two arrays are equal.
[run-phpunit:L19:2s] --- Expected
[run-phpunit:L20:2s] +++ Actual
[run-phpunit:L21:2s] @@ @@
[run-phpunit:L22:2s]  Array (
[run-phpunit:L23:2s] +    0 => OC\Lock\Persistent\Lock Object (...)
[run-phpunit:L24:2s] 
[run-phpunit:L25:2s] /drone/src/owncloud/tests/lib/Files/Storage/LockingTests.php:100
```

with `FROM=10.1.0 DB_TYPE=sqlite TO=daily-stable10-qa drone exec`

this confirms that the locks likely exist from before the upgrade and are not due to unit test side effects

**Comment by PVince81** [comment]
I checked the oc_persistent_locks table before phpunit run (sleep before phpunit) and that table is empty...

**Comment by PVince81** [comment]
`testGetLocks` is the one and only test within that file. So no other possible side effects.

So it seems there is some :ghost:  that fiddles with the oc_persistent_locks table between the start of phpunit until it reaches this test.

**Comment by PVince81** [comment]
Looking further into the test: the failure happens at the very last assert.
Basically the test is setting some locks, checking for their existence, then releasing them. The last assert, which fails, is the one that verifies that unlocking actually happened.

So the problem seems to lie in the unlocking routine: https://github.com/owncloud/core/blob/stable10/tests/lib/Files/Storage/LockingTests.php#L94

We seem to be using real storage here instead of a mock (which is needed in many test scenarios), so this could also be related to the underlying the storage.
Or it's a thing of the SQLite DB that the clearing isn't done.

Needs further debugging.

**Comment by PVince81** [comment]
after phpunit run:
```
sqlite> select * from oc_persistent_locks;
id|file_id|owner_account_id|owner|timeout|created_at|token|token_hash|scope|depth
1|10|2|locking-user|1800|1557493760|123-456-789|856f4f9c3c084d978ec7ea0ad7d4cadf|1|0
```

**Comment by PVince81** [comment]
```
// by property_get
$query                           = (string[94]) 'DELETE FROM "oc_persistent_locks" WHERE ("file_id" = :dcValue1) AND ("token_hash" = :dcValue2)';


// by property_get
$params                          = (array[2]);
  $params["dcValue1"]            = (string[2]) '26';
  $params["dcValue2"]            = (string[32]) '856f4f9c3c084d978ec7ea0ad7d4cadf';
```
DB:
```
sqlite> select * from oc_persistent_locks;
id|file_id|owner_account_id|owner|timeout|created_at|token|token_hash|scope|depth
4|26|6|locking-user|1800|1557494709|123-456-789|856f4f9c3c084d978ec7ea0ad7d4cadf|1|0
```

The DELETE call returns 0 update rows when done from PHP, despite all arguments matching...


Manual attempt:
```
sqlite> delete from oc_persistent_locks where ("file_id" = "26") AND ("token_hash" = "856f4f9c3c084d978ec7ea0ad7d4cadf");
sqlite> select * from oc_persistent_locks;
id|file_id|owner_account_id|owner|timeout|created_at|token|token_hash|scope|depth
4|26|6|locking-user|1800|1557494709|123-456-789|856f4f9c3c084d978ec7ea0ad7d4cadf|1|0
```

The problem is that the fileid is passed in as string.
If I replace `"26"` with `26` the query goes through.

**Comment by PVince81** [comment]
In this Drone container, the following versions are used:
- php 7.1.27-1+ubuntu16.04.1+deb.sury.org+1
- sqlite3 3.11.0-1ubuntu1.1

**Comment by PVince81** [comment]
on my local env the test passes fine.

however if I test the deletion with fileid as string on the CLI sqlite3 locally it also doesn't delete.

I didn't actually see the full query and just guessed that it was a string vs int issue.

Need to confirm by adding a cast.

**Comment by PVince81** [comment]
In the Drone source I tried casting the $fileid from string to int in the LockMapper, but the deletion still didn't work. So it's not a casting issue.
Need to dig even deeper into that query...

**Comment by PVince81** [comment]
in the Drone env it's still using binding type 2 (string) despite the value being an int...

I can't dig deeper than that as it reaches the DB API calls.

**Comment by PVince81** [comment]
this fixes the issue:
```
diff --git a/lib/private/Lock/Persistent/LockMapper.php b/lib/private/Lock/Persistent/LockMapper.php
index e84009f99f..2659f5481e 100644
--- a/lib/private/Lock/Persistent/LockMapper.php
+++ b/lib/private/Lock/Persistent/LockMapper.php
@@ -157,7 +157,7 @@ class LockMapper extends Mapper {
                $query = $this->db->getQueryBuilder();
 
                $rowCount = $query->delete($this->getTableName())
-                       ->where($query->expr()->eq('file_id', $query->createNamedParameter($fileId)))
+                       ->where($query->expr()->eq('file_id', $query->createNamedParameter($fileId, $type = \PDO::PARAM_INT)))
                        ->andWhere($query->expr()->eq('token_hash', $query->createNamedParameter(\md5($token))))
                        ->execute();
```

but it doesn't explain why it works locally and in CI...

I wonder if there is something bug in that PHP version that was solved later on...

**Comment by PVince81** [comment]
I have now hacked the drone.yml to run this one unit test directly on the QA tarball.

the test passes... so this rules out an environment issue.

so it looks like the issue is indeed related to an update.

next up: examine detailed DB schema for that table...

**Comment by PVince81** [comment]
DB dump (grepped) before upgrade:
```
CREATE TABLE oc_filecache (fileid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, storage INTEGER DEFAULT 0 NOT NULL, path VARCHAR(4000) DEFAULT NULL COLLATE BINARY, path_hash VARCHAR(32) DEFAULT '' NOT NULL COLLATE BINARY, parent BIGINT DEFAULT 0 NOT NULL, name VARCHAR(250) DEFAULT NULL COLLATE BINARY, mimetype INTEGER DEFAULT 0 NOT NULL, mimepart INTEGER DEFAULT 0 NOT NULL, size BIGINT DEFAULT 0 NOT NULL, encrypted INTEGER DEFAULT 0 NOT NULL, unencrypted_size BIGINT DEFAULT 0 NOT NULL, etag VARCHAR(40) DEFAULT NULL COLLATE BINARY, permissions INTEGER DEFAULT 0, checksum VARCHAR(255) DEFAULT NULL COLLATE BINARY, mtime BIGINT DEFAULT 0 NOT NULL, storage_mtime BIGINT DEFAULT 0 NOT NULL);
INSERT INTO "oc_filecache" VALUES(1,2,'','d41d8cd98f00b204e9800998ecf8427e',-1,'',2,1,-1,0,0,'5cd590646d18d',23,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(2,2,'avatars','aec9f4efc5a055bbd053f220538c61e0',1,'avatars',2,1,0,0,0,'5cd5906436a0c',31,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(3,2,'avatars/21','ad6861de6e7fc46a455df0acc3655dec',2,'21',2,1,0,0,0,'5cd5906436a0c',31,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(4,2,'avatars/21/23','cb64392e5da27306a608dc0195e783f7',3,'23',2,1,0,0,0,'5cd5906436a0c',31,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(5,2,'avatars/21/23/2f297a57a5a743894a0e4a801fc3','529dc0f71e29aa0491601dcd32bdd56d',4,'2f297a57a5a743894a0e4a801fc3',2,1,0,0,0,'5cd59064353f9',31,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(6,2,'files_external','c270928b685e7946199afdfb898d27ea',1,'files_external',2,1,0,0,0,'5cd590646a13f',31,'',1557500004,1557500004);
INSERT INTO "sqlite_sequence" VALUES('oc_filecache',6);
CREATE INDEX fs_storage_size ON oc_filecache (storage, size, fileid);
CREATE INDEX fs_storage_mimepart ON oc_filecache (storage, mimepart);
CREATE INDEX fs_storage_mimetype ON oc_filecache (storage, mimetype);
CREATE INDEX fs_parent_name_hash ON oc_filecache (parent, name);
CREATE UNIQUE INDEX fs_storage_path_hash ON oc_filecache (storage, path_hash);
(...)
CREATE TABLE oc_persistent_locks (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, file_id BIGINT NOT NULL, owner_account_id BIGINT UNSIGNED DEFAULT NULL, owner VARCHAR(100) DEFAULT NULL, timeout INTEGER UNSIGNED NOT NULL, created_at INTEGER UNSIGNED NOT NULL, token VARCHAR(1024) NOT NULL, token_hash VARCHAR(32) NOT NULL, scope SMALLINT NOT NULL, depth SMALLINT NOT NULL);
CREATE UNIQUE INDEX UNIQ_F0C3D55BB3BC57DA ON oc_persistent_locks (token_hash);
CREATE INDEX IDX_F0C3D55B93CB796C ON oc_persistent_locks (file_id);
CREATE INDEX IDX_F0C3D55BC901C6FF ON oc_persistent_locks (owner_account_id);
```

After the upgrade:
```
CREATE TABLE oc_filecache (fileid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, storage INTEGER DEFAULT 0 NOT NULL, path VARCHAR(4000) DEFAULT NULL COLLATE BINARY, path_hash VARCHAR(32) DEFAULT '' NOT NULL COLLATE BINARY, parent BIGINT DEFAULT 0 NOT NULL, name VARCHAR(250) DEFAULT NULL COLLATE BINARY, mimetype INTEGER DEFAULT 0 NOT NULL, mimepart INTEGER DEFAULT 0 NOT NULL, size BIGINT DEFAULT 0 NOT NULL, encrypted INTEGER DEFAULT 0 NOT NULL, unencrypted_size BIGINT DEFAULT 0 NOT NULL, etag VARCHAR(40) DEFAULT NULL COLLATE BINARY, permissions INTEGER DEFAULT 0, checksum VARCHAR(255) DEFAULT NULL COLLATE BINARY, mtime BIGINT DEFAULT 0 NOT NULL, storage_mtime BIGINT DEFAULT 0 NOT NULL);
INSERT INTO "oc_filecache" VALUES(1,2,'','d41d8cd98f00b204e9800998ecf8427e',-1,'',2,1,-1,0,0,'5cd590646d18d',23,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(2,2,'avatars','aec9f4efc5a055bbd053f220538c61e0',1,'avatars',2,1,0,0,0,'5cd5906436a0c',31,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(3,2,'avatars/21','ad6861de6e7fc46a455df0acc3655dec',2,'21',2,1,0,0,0,'5cd5906436a0c',31,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(4,2,'avatars/21/23','cb64392e5da27306a608dc0195e783f7',3,'23',2,1,0,0,0,'5cd5906436a0c',31,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(5,2,'avatars/21/23/2f297a57a5a743894a0e4a801fc3','529dc0f71e29aa0491601dcd32bdd56d',4,'2f297a57a5a743894a0e4a801fc3',2,1,0,0,0,'5cd59064353f9',31,'',1557500004,1557500004);
INSERT INTO "oc_filecache" VALUES(6,2,'files_external','c270928b685e7946199afdfb898d27ea',1,'files_external',2,1,0,0,0,'5cd590646a13f',31,'',1557500004,1557500004);
INSERT INTO "sqlite_sequence" VALUES('oc_filecache',6);
CREATE UNIQUE INDEX fs_storage_path_hash ON oc_filecache (storage, path_hash);
CREATE INDEX fs_parent_name_hash ON oc_filecache (parent, name);
CREATE INDEX fs_storage_mimetype ON oc_filecache (storage, mimetype);
CREATE INDEX fs_storage_mimepart ON oc_filecache (storage, mimepart);
CREATE INDEX fs_storage_size ON oc_filecache (storage, size, fileid);
(...)
CREATE TABLE oc_persistent_locks (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, file_id BIGINT NOT NULL, owner_account_id BIGINT UNSIGNED DEFAULT NULL, owner VARCHAR(100) DEFAULT NULL COLLATE BINARY, timeout INTEGER UNSIGNED NOT NULL, created_at INTEGER UNSIGNED NOT NULL, token VARCHAR(1024) NOT NULL COLLATE BINARY, token_hash VARCHAR(32) NOT NULL COLLATE BINARY, scope SMALLINT NOT NULL, depth SMALLINT NOT NULL);
INSERT INTO "sqlite_sequence" VALUES('oc_persistent_locks',0);
CREATE INDEX IDX_F0C3D55BC901C6FF ON oc_persistent_locks (owner_account_id);
CREATE INDEX IDX_F0C3D55B93CB796C ON oc_persistent_locks (file_id);
CREATE UNIQUE INDEX UNIQ_F0C3D55BB3BC57DA ON oc_persistent_locks (token_hash);
```

The only difference I found is that the following columns in oc_persistent_locks have "COLLATE BINARY" in them after the upgrade:
- owner
- token
- token_hash

I wonder if this makes Sqlite maybe switch to a different matching mode for the other columns ?

I do wonder what is triggering the collation update though as I don't think we changed anything related between 10.1.0 and stable10... Could be one of the repair step which does collation stuff but doesn't do so at setup time ?!

**Comment by PVince81** [comment]
collation repair only for MySQL, so not relevant here: https://github.com/owncloud/core/blob/stable10/lib/private/Repair/Collation.php#L59

**Comment by PVince81** [comment]
no doctrine/dbal differences between v10.1.0 and stable10 branches

**Comment by PVince81** [comment]
I think I've landed in weirdland...

After the upgrade, the DB file is in a specific state in which the phpunit test fails.
Then I dump the DB.
Then I drop "oc_persistent_locks".
Then I run all the dump's schema SQL commands for "oc_persistent_locks".
Then I run the tests: they pass...

**Comment by PVince81** [comment]
Let's call "broken database" the database state after the upgrade where it behaves strangely.

At this point it is unclear to me whether it's:

1) a PDO bug where "string" doesn't automatically get converted to "int" for the "broken database". There could be hidden state data somewhere that influences that.

or

2) a Sqlite bug where "string" doesn't automatically get converted ot "int" for the "broken database". From what I read, PDO would just send the query and parameters as is and the DB engine might convert them.

I don't understand why recreating the table with the exact same schema + indices from the dump solves the issue. Maybe there is stray data hidden somewhere in the Sqlite b-tree structure that gets erased during recreation. And maybe said data influences or triggers the bug above.

Again: the bug only occurs inside the drone instance from the upgrade.

If I copy the database over into a local instance, the test runs fine.

I'm not sure if we should continue digging or simply add a workaround.
Maybe the local env has an updated PHP / PDO / sqlite where said bug was fixed.

**Comment by PVince81** [comment]
another worry I have is that if this table can get into such weird state, can other tables too ??

**Comment by PVince81** [comment]
and which part of our upgrade routine is causing this weird state ?
and why does the schema has "COLLATE binary" on some columns after OC upgrade but not before or on initial setup ?

**Comment by PVince81** [comment]
I've now removed sqlite for now.

- [ ] TODO: raise ticket to investigate further

**Comment by PVince81** [comment]
raised https://github.com/owncloud/update-testing/issues/22 to investigate sqlite separately

**Comment by PVince81** [comment]
@patrickjahns all green, merge ?

**Pull request merged**
